jobs:
    - job: terraform_destroy
      steps:
        - task: TerraformInstaller@0
          enabled: false
          displayName: 'install'
          inputs:
            terraformVersion: '${{ parameters.terraform_version }}'
        - task: TerraformTaskV3@3
          displayName: 'init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: '${{ parameters.backendServiceArm }}'
            backendAzureRmResourceGroupName: '${{ parameters.backendAzureRmResourceGroupName }}'
            backendAzureRmStorageAccountName: '${{ parameters.backendAzureRmStorageAccountName }}'
            backendAzureRmContainerName: '${{ parameters.backendAzureRmContainerName }}'
            backendAzureRmKey: '${{ parameters.backendAzureRmKey }}' 
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        - task: TerraformTaskV3@3
          displayName: 'destroy'
          condition: and(succeeded(), eq(variables['action'], 'Destroy'))
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            commandOptions: '-input=false -auto-approve -var-file="${{ parameters.environment }}.tfvars"'
            environmentServiceNameAzureRM: '${{ parameters.backendServiceArm }}'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
